# Generated by Django 3.2.9 on 2021-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total_page', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
