# Generated by Django 3.2.9 on 2021-11-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Book',
        ),
    ]
